---
title: "Taller 4"
author: 
- Juan Sosa PhD
- Webpage https://sites.google.com/view/juansosa/ 
- YouTube https://www.youtube.com/c/JuanSosa1702 
- GitHub  https://github.com/jstats1702 
- Rpubs   https://rpubs.com/jstats1702
date: ""
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Redes de poder en Colombia {-}

La base de datos `poder` disponible en la página web del curso corresponde a una red bipartita que relaciona funcionarios públicos con las entidades públicas en las que fueron nombrados a lo largo de seis gobiernos de Colombia, Uribe 1, Uribe 2, Santos 1, Santos 2, Duque y Petro. Específicamente, estos datos se representan mediante una matriz bipartita $\mathbf{A}=[a_{i,j}]$ de tamaño $n \times m$, donde $n$ representa el número de funcionarios y $m$ el número de entidades públicas. En esta matriz, $a_{i,j}=1$ si el funcionario $i$ fue nombrado en la entidad $j$, y $a_{i,j}=0$ en caso contrario. La base también incluye covariables individuales, como `EDAD`, `GENERO`, `PARTIDO_POLITICO`, `NIVEL_DE_ESTUDIOS`, `UNIVERSIDAD`, `CARRERA` y `GOBERNACION`. Esta información fue diseñada y recolectada junto con el estudiante Johan Andrés Hernández Sarmiento como parte de su trabajo de grado. La base tiene carácter estrictamente confidencial, por lo que ninguna persona cuenta con autorización para compartirla, reproducirla o divulgarla.

El objetivo es llevar a cabo un análisis exhaustivo de las redes de poder en Colombia a través de distintos gobiernos. En el artículo [Estos son los grupos políticos que sostienen al gobierno Petro y sus puntos de tensión](https://www.pares.com.co/estos-son-los-grupos-politicos-que-sostienen-al-gobierno-petro-y-sus-puntos-de-tension/), los autores desarrollan un ejercicio similar, aunque a una escala mucho menor y con recursos teóricos, empíricos y metodológicos más limitados desde el punto de vista del análisis de redes. A pesar de su simplicidad técnica, este texto constituye un buen punto de partida para comprender el propósito general de este caso de estudio.

a. Filtre la base de datos usando la covariable `GOBERNACION`, de manera que se conserven todos aquellos funcionarios que hicieron parte del Gobierno Petro, incluso si también participaron en otros gobiernos. Sea $\mathbf{A}_{\text{P}}$ la matriz bipartita resultante de este filtro, de tamaño $n_{\text{P}} \times m$, donde $n_{\text{P}}$ corresponde al número de funcionarios del Gobierno Petro y $m$ corresponde al número de entidades públicas. A partir de esta matriz, construya la matriz de adyacencia ponderada $\mathbf{A}_{\text{P}}\mathbf{A}_{\text{P}}^\top$, de tamaño $n_{\text{P}} \times n_{\text{P}}$. Luego, construya la matriz $\mathbf{Y}_{\text{P}}$ a partir de esta matriz de adyacencia ponderada, transformándola en una matriz binaria y fijando en cero los elementos de la diagonal principal. Repita este procedimiento para los gobiernos Duque, Santos y Uribe. En los casos de Santos y Uribe, combine los dos periodos de cada gobierno en una sola matriz. Al finalizar el proceso, debe contar con cuatro redes binarias no dirigidas, una para cada gobierno.

b. De manera paralela y comparativa, construya visualizaciones decoradas para cada red, aprovechando al máximo la información nodal disponible. Presente estas visualizaciones de forma estratégica, de modo que faciliten la comparación entre gobiernos y permitan identificar patrones comunes, diferencias estructurales y posibles cambios en la configuración de las redes de poder.

c. Calcule medidas de centralidad para identificar cuáles son los funcionarios más influyentes dentro de cada red. A partir de estos resultados, construya visualizaciones decoradas que incorporen la información de centralidad de manera clara e informativa. Presente las visualizaciones de forma estratégica para comparar los resultados entre gobiernos. Finalmente, interprete los hallazgos de manera profunda, pero concisa, destacando sus posibles implicaciones políticas.

d. Analice cada una de las redes a nivel local y estructural mediante métricas de distancia, cohesión, conectividad y agrupamiento. Emplee un conjunto amplio de métricas que permita caracterizar de manera detallada las propiedades principales de cada red. Presente los resultados de forma estratégica, de modo que se facilite la comparación entre gobiernos y se identifiquen similitudes, diferencias y cambios relevantes en la estructura de las redes de poder. Finalmente, interprete los hallazgos de manera profunda, pero concisa, destacando sus posibles implicaciones políticas.

e. Ajuste, de manera independiente para cada red, un modelo de bloques estocásticos, un modelo de grafos aleatorios exponenciales y un modelo de socialidad con covariables. En el caso del modelo de grafos aleatorios exponenciales, incluya como términos del predictor lineal el número de aristas y las covariables con efectos homofílicos. Para el modelo de socialidad, incorpore también covariables con efectos homofílicos. Presente todos los resultados de forma estratégica, de modo que se facilite la comparación entre gobiernos y se identifiquen diferencias relevantes en la estructura de las redes de poder. Finalmente, interprete los resultados de manera profunda, pero concisa, destacando sus posibles implicaciones políticas.

f. Evalúe la bondad de ajuste de los modelos ajustados en el numeral anterior utilizando como estadísticos de prueba la densidad, la transitividad, la asortatividad y la distancia geodésica promedio. Presente los resultados en tablas y gráficos, interpretando detalladamente los hallazgos, identificando qué modelos capturan mejor las propiedades observadas en la red y limitando el análisis a un máximo de 1000 palabras.

g. Repita los numerales b., c. y d. para la red completa, sin filtrar por gobierno.

## Estructuras sociales cognitivas {-}

El trabajo de David Krackhardt en la década de 1980 fue pionero en la identificación de individuos con habilidades para percibir la estructura social en la que están inmersos. Para ello, recopiló datos relacionales sobre la estructura social cognitiva (*Cognitive Social Structure*, CSS, por sus siglas en inglés) de 21 miembros del personal administrativo de una empresa de fabricación de maquinaria de alta tecnología, Silicon Systems. El objetivo era evaluar los efectos de un programa reciente de intervención administrativa. Una de las relaciones estudiadas fue la amistad, donde cada persona no solo reportó sus relaciones de amistad, sino también las relaciones percibidas entre todos los demás empleados. Esto permitió construir una matriz de adyacencia de tamaño $21 \times 21$ que reflejaba las percepciones de cada individuo dentro del grupo. Este enfoque ha sido utilizado con éxito en estudios posteriores mediante modelos triádicos (e.g., Sosa y Rodríguez 2021).

Para replicar los hallazgos de Krackhardt, así como de otros autores que han estudiado las estructuras sociales cognitivas (*CSSs*), considere el conjunto de datos `CSS2022.txt`. Este archivo contiene las percepciones de amistad de los estudiantes de un curso ofrecido por el Departamento de Estadística de la Universidad Nacional de Colombia durante el segundo semestre de 2022.  

El archivo incluye una CSS completa de dimensión 15, conformada por quince matrices de adyacencia de tamaño $15 \times 15$. Cada matriz $\mathbf{A}^{(j)}$ representa la percepción del estudiante $j$ sobre las relaciones de amistad en el sistema social del curso, con $j=1, \ldots, 15$. Además, el archivo `covs.txt` proporciona información adicional sobre cada estudiante: sexo (0 = Mujer, 1 = Hombre), edad (edad en años cumplidos) y texttt{programa (0 = Pregrado, 1 = Posgrado).  

La red de consenso de una CSS se define como la red cuya matriz de adyacencia, denotada por $\mathbf{A} = [a_{i,j}]$, se construye aplicando la siguiente regla:  
\[
a_{i,j} = 
\begin{cases} 
1, & \text{si } \frac{1}{I} \sum_{k=1}^I a_{i,j,k} > 0.25, \\
0, & \text{en otro caso},
\end{cases}
\]
donde $I$ es el número total de actores en el sistema, y $a_{i,j,k}$ es la percepción del actor $k$ sobre la relación entre los actores $i$ y $j$.  

Este enfoque permite sintetizar las percepciones individuales en una única red que refleja el consenso del sistema social en cuestión.  

a. Realice visualizaciones no decoradas en un diseño circular para representar todas las percepciones individuales y la red de consenso. Compare las diferencias entre las percepciones individuales y entre estas y la red de consenso, identificando posibles discrepancias o patrones consistentes. Use tantas tablas y gráficos como sean necesarios para apoyar el análisis. Interprete los resultados obtenidos, evaluando la coherencia entre las percepciones y la capacidad del consenso para capturar el panorama general del sistema social, limitando el análisis a un máximo de 1000 palabras.

b. Realice un análisis descriptivo detallado de la red de consenso, destacando sus propiedades estructurales y métricas clave como densidad, transitividad, distribución de grados, entre otras. Utilice tablas y gráficos según sea necesario para presentar la información de manera clara y organizada. Interprete los resultados obtenidos, destacando los patrones relevantes y su implicación en el contexto del estudio, limitando el análisis a un máximo de 1000 palabras.

c. Calcule el grado normalizado para cada actor en todas las percepciones individuales y en la red de consenso. Construya diagramas de caja para cada actor, mostrando la distribución de su grado a través de las percepciones y el consenso. Distinga el grado basado en la percepción propia de cada actor con un triángulo rojo ($\triangle$) y el grado basado en la red de consenso con una cruz azul ($\times$). Incluya todos los diagramas de caja en un único gráfico. Un ejemplo de este tipo de gráfico puede encontrarse en [este enlace](https://arxiv.org/pdf/1711.03662.pdf), página 9. Analice si los actores tienen una percepción adecuada de su rol dentro del sistema social y limite la interpretación de los resultados a un máximo de 1000 palabras.

d. Ajuste un modelo de grafos aleatorio exponencial a la red de consenso, utilizando como términos en el predictor lineal el número de aristas y las covariables con efectos homofílicos. Realice una interpretación detallada de los resultados obtenidos, identificando el impacto de las covariables en la estructura de la red y discutiendo la adecuación del modelo en este contexto. Limite la interpretación a un máximo de 1000 palabras.

e. Considere los siguientes modelos (sin covariables) para ajustarlos a la red de consenso:  
     1. **$\textsf{M}_1$: Modelo de grafos aleatorios.**  
     2. **$\textsf{M}_2$: Modelo de grafos aleatorios generalizado.**  
     3. **$\textsf{M}_3$: Modelo de grafos aleatorio exponencial con número de aristas y triángulos.** 
     4. **$\textsf{M}_4$: Modelo de bloques estocásticos.**  
     5. **$\textsf{M}_5$: Modelo latente de distancia clásico con dos dimensiones latentes.**
     6. **$\textsf{M}_6$: Modelo de sociabilidad.**

     Ajuste cada uno de estos modelos y utilice tablas y visualizaciones según sea necesario para mostrar los resultados. Interprete detalladamente los hallazgos de cada modelo, sin límite de palabras para esta sección, destacando las fortalezas y limitaciones de cada enfoque.
     
     Nota: El modelo de sociabilidad se encuentra disponible en https://rpubs.com/jstats1702/1430765 (este modelo lo publicaron en 2026 Sosa y Martínez en https://www.tandfonline.com/doi/full/10.1080/10618600.2026.2627454).

f. Evalúe la bondad de ajuste de los modelos ajustados en el numeral anterior utilizando como estadísticos de prueba la densidad, la transitividad, la asortatividad y la distancia geodésica promedio. Presente los resultados en tablas y gráficos, interpretando detalladamente los hallazgos, identificando qué modelos capturan mejor las propiedades observadas en la red de consenso y limitando el análisis a un máximo de 1000 palabras.

g. Compruebe la capacidad predictiva de los modelos ajustados en el numeral anterior mediante validación cruzada con cinco (*5 folds*). Evalúe el rendimiento predictivo de cada modelo, utilizando tablas y gráficos para resumir los resultados. Interprete los hallazgos, destacando cuál modelo proporciona las mejores predicciones y por qué, limitando la interpretación a un máximo de 1000 palabras.


## Mafia {-}

El objetivo de este taller es analizar la estructura de una red social derivada de la orden de detención preventiva emitida por el Tribunal de Messina en marzo de 2007, en el marco de la operación anti mafia “Montagna”. La investigación se centró en la familia “Mistretta” y el clan “Batanesi”, que infiltraron diversas actividades económicas entre 2003 y 2007. Los datos se encuentran en el archivo `mafia.RData`. La red representa individuos y relaciones asociadas con actividades ilícitas, donde los nodos corresponden a personas o entidades y los arcos a relaciones de influencia o interacción. La red es dirigida y ponderada.

a. Explorar la estructura de los datos de nodos y aristas, identificar la información relevante para el análisis, verificar si la red es simple y ponderada, construir la red, calcular su orden y tamaño, generar una visualización inicial e identificar los nodos más conectados.

b. Analizar la estructura global de la red mediante el grado nodal, la conectividad, los componentes, el diámetro y las distancias geodésicas, complementando el estudio con una visualización en la que los nodos se distingan por clan y tamaño según su grado.

c. Evaluar la importancia estructural de los nodos mediante grado, fuerza y medidas de centralidad, estudiar la cohesión de la red a través de cliques, densidad y transitividad, y apoyar la interpretación con visualizaciones adecuadas.

d. Aplicar y comparar métodos de detección de comunidades, evaluar la modularidad de las particiones, analizar la asortatividad por grado y por clan si corresponde, contrastar las comunidades detectadas con los clanes conocidos y visualizar la partición más adecuada.

e. Ajustar los modelos considerados previamente incorporando la información nodal relevante cuando sea pertinente, presentar e interpretar sus resultados mediante tablas y gráficos, evaluar su bondad de ajuste con base en densidad, transitividad, asortatividad y distancia geodésica promedio, y comparar su capacidad predictiva mediante validación cruzada de 5 particiones. Las secciones de bondad de ajuste y capacidad predictiva deben tener una extensión máxima de 1000 palabras cada una.


# Referencias {-}

Kolaczyk, E. D., & Csárdi, G. (2020). Statistical analysis of network data with R (Vol. 65). New York: Springer.

Luke, D. A. (2015). A user's guide to network analysis in R (Vol. 72, No. 10.1007, pp. 978-3). Cham: Springer.

Sosa, J., & Rodríguez, A. (2021). A latent space model for cognitive social structures data. Social Networks, 65, 85-97.

